services:
  - docker
addons:
  organization: 'inseefrlab'
script:
  - docker build -t inseefrlab/ubuntu-vnc-dind .
deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/ubuntu-vnc-dind
  on:
    branch: master
